language: node_js
node_js:
  - node
before_install:
  # Install zookeeper
  - wget https://archive.apache.org/dist/zookeeper/zookeeper-3.4.9/zookeeper-3.4.9.tar.gz
  - tar xzf zookeeper-3.4.9.tar.gz
  - echo "tickTime=2000" > zookeeper-3.4.9/conf/zoo.cfg
  - echo "dataDir=/tmp/zookeeper" >> zookeeper-3.4.9/conf/zoo.cfg
  - echo "clientPort=2181" >> zookeeper-3.4.9/conf/zoo.cfg
  - mkdir /tmp/zookeeper
  - zookeeper-3.4.9/bin/zkServer.sh start
install:
  - npm install
script:
  - npm run test
